"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$time\
$directory\
[»](fg:color_pink)\
$git_branch\
$git_status\
[»](fg:color_pastel_pink)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
[» ](fg:color_pastel_pink)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = 'tu'

[palettes.tu]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_cyan = '#00ffff'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_white = '#ffffff'
color_pink = '#ffc0cb'
color_light_pink = '#ffb6c1'
color_dark_pink = '#e75480'
color_hot_pink = '#ff10f0'
color_pastel_pink = '#ffd1dc'

style = "bold color_hot_pink"

[character]
success_symbol = "[󰄬](bold color_green)"
error_symbol = "[󰅚](bold color_red)"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false
style = "fg:color_pink"
[os.symbols]
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
HardenedBSD = ""
Illumos = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
OracleLinux = ""
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[username]
show_always = true
style_user = "fg:color_pastel_pink"
style_root = "fg:color_red"
format = '[ ♥ ]($style)'
disabled = false

[sudo]
symbol = "󰀐 "
style = "bold color_hot_pink"
disabled = false
format = '[$symbol]($style)'

[time]
disabled = false
time_format = "%H:%M:%S" # Hour:Minute Format
style = "fg:color_pink"
format = '[$time ]($style)'

[directory]
style = "bold color_cyan"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[custom.dotfiles]
detect_files = ['.bash_style']
symbol = "󱁊"
style = "bold color_pastel_pink"
format = "[$symbol]($style)"

[git_branch]
symbol = ""
style = "fg:color_cyan"
format = '[$symbol$branch]($style)'
[git_status]
style = "fg:color_cyan"
conflicted = "[󰞇 CONFLICT](bold color_hot_pink) "
deleted = "[󰗨](fg:color_hot_pink) "
format = '[$all_status$ahead_behind]($style)'

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
[[battery.display]]
threshold = 15
style = "bold color_white"
[[battery.display]]
threshold = 100
style = "fg:color_cyan"

[cmd_duration]
min_time = 2_000
style = "fg:color_pastel_pink"
format = "[󱎫 $duration]($style)"

# Languages
[c]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[cpp]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[docker_context]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol $context]($style)'

[elixir]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[elm]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[golang]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[gradle]
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[haskell]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[java]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[julia]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[nodejs]
symbol = ""
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[nim]
symbol = "󰆥 "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[rust]
symbol = ""
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'

[scala]
symbol = " "
style = "fg:color_cyan"
format = '[$symbol($version)]($style)'
